### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Evolution0** [Evolution0/bandcamp-dl#70]
0.0.6
----
- [x] Individual track downloads (KeyError: 'album_title')
Note: Could use more testing, but haven't run into issues yet.
- [x] `--no-art` option

On hold:
----
- [ ] `--embed-lyrics` option
Note: Duplicates lyrics (adds a second Lyrics tag) even if lyrics already exist.

**Comment by Evolution0** [comment]
Should it simply go: 0.0.5 -> 0.0.6? I figured a jump to python 3 justified a bigger increment and the version numbering has been kinda.. weird to begin with really, on PyPI it goes by the version specified in the setup.py but the actual bandcamp_dl.py specifies it as 1.0.

Its possible it could be re-versioned entirely and resubmitted to PyPI as bandcamp-dl which would look nice and match the script + repo name but that is entirely up to you @iheanyi

**Comment by Evolution0** [comment]
My current idea is to port my fixes to the Python 2 codebase, move it to a branch then make the new Python 3 code the master. 

Another possibility is to append the filenames with -py2/-py3 and configure the setup.py to build multiple wheels. Downside is we would end up dragging the Python 2 codebase along for some time, and eventually something will not be able to be ported. (Async stuff, soon-ish)

**Comment by iheanyi** [comment]
I think that's a great plan of attack. Honestly, I'm all for dropping Python 2.7 support, although I'd have to reconfigure packaging for Python 3, wouldn't I?

**Comment by iheanyi** [comment]
Also, what are your thoughts on maybe developing a small website for this project? I can whip something up if you think it'd be valuable and after we get the build story ironed out.

**Comment by Evolution0** [comment]
Making a [Project Page](https://help.github.com/articles/user-organization-and-project-pages/#project-pages) for it seems the simplest route, and since it would be contained in the project repo its easily managable. Maybe take a look at a static site generator like Pelican/Jekyl/Hyde/Nicola.

As for re-configuring packaging I've already made a new setup.py following PyPI's example project:
https://github.com/Evolution0/bandcamp-dl/blob/master/setup.py
(Don't mind the reference to Python 2.7, the idea to split the repo came after I made this)

**Comment by iheanyi** [comment]
Works for me. Do you think we need CI and release tagging for this?

**Comment by Evolution0** [comment]
Release tagging might be good, that way people can get the source to specific builds pushed to PyPI rather than just clone the repo and hope its the same (or even working)

As for CI.. I have no idea how that works, I actually don't have much experience writing tests but I suppose getting a nice list of unique urls (ones we previously had issues with) and running through all of them (and with various `options`) getting the output then writing some asserts for the expected output and running it through pytest should work right?

**Comment by iheanyi** [comment]
Yeah, exactly re: release tagging. :)

And yeah, CI is complicated but it's only complicated as it needs to be. :) But essentially, yes. It's just getting some inputs (mock JSON or HTML from Bandcamp), inserting it into the tests and using it to make sure functions work as expected. I've never written tests in Python outside of Django before, so it'd be a new experience to me as well, haha.

**Comment by Evolution0** [comment]
Alright, Python 2 branch has been pushed.

I made sure the Python 2 branch is 1:1 with my Python 3 fork, nice and neat. They both have the same bug fixes and features. I even managed to restore some code that I somehow missed to the Python 3 fork (Track index message)

You may get a lextab/yacctab warning, this is a weird bug with Ply that has been mentioned before, it is completely harmless and due to it not being able to overwrite the included lextab/yacctab included with slimit (Which makes no sense, they are generated and should not be included) you can make it go away by deleting those two files from /site-packages/slimit/

In reality the Python 2 and 3 versions now have the same code and dependency versions.

Edit: Wait a minute, I think I just made it cross-compatible without even realizing it.. yep, looks like I did. Guess I'll edit the setup.py with both Python tags at least for this version, when it comes time that the master branch uses features that Python 2 does not support I'll simply stop updating that branch and edit the setup.py for the master.

I made a PR with a more sane solution to updating the current master, Id rather retain the commit history when merging rather than clone the master and simply copy-paste my fork.
